name: et-masterclass
channels:
  - conda-forge/label/calliope_dev
  - conda-forge
  - gurobi
dependencies:
  - python=3.12
  - matplotlib=3.9.2
  - jupyterlab
  - glpk=5.0
  - gurobi=11.0
  - calliope=0.7.0dev4
  - pyproj==3.6.1
  - panel>=1.5.2,<1.6
  - plotly>=5,<6
  - pip
  - pip:
    - git+https://github.com/calliope-project/calligraph.git@v0.1.1.dev4